services:

  postgres:
    image: postgres:latest
    container_name: airline_postgres
    environment:
      POSTGRES_USER: airline
      POSTGRES_PASSWORD: airline123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airline"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: airline_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: airline_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "airline"
      RABBITMQ_DEFAULT_PASS: "airline123"
    ports:
      - "5672:5672"
      - "15672:15672"

  api-gateway:
    build: ./ApiGateway
    container_name: airline_gateway
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=AirlineBooking_SuperSecret_JWT_Key_2024!
      - Jwt__Issuer=AuthService
      - Jwt__Audience=AirlineBookingApp
    depends_on:
      auth-service:
        condition: service_started
      flight-service:
        condition: service_started
      seat-service:
        condition: service_started
      booking-service:
        condition: service_started
      passenger-service:
        condition: service_started
      notification-service:
        condition: service_started

  auth-service:
    build: ./AuthService
    container_name: airline_auth
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=AirlineAuth;Username=airline;Password=airline123;
      - Jwt__Key=AirlineBooking_SuperSecret_JWT_Key_2024!
      - Jwt__Issuer=AuthService
      - Jwt__Audience=AirlineBookingApp
    depends_on:
      postgres:
        condition: service_healthy

  flight-service:
    build: ./FlightService
    container_name: airline_flight
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=AirlineFlight;Username=airline;Password=airline123;
      - Jwt__Key=AirlineBooking_SuperSecret_JWT_Key_2024!
      - Jwt__Issuer=AuthService
      - Jwt__Audience=AirlineBookingApp
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  seat-service:
    build: ./SeatService
    container_name: airline_seat
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=AirlineSeat;Username=airline;Password=airline123;
      - Jwt__Key=AirlineBooking_SuperSecret_JWT_Key_2024!
      - Jwt__Issuer=AuthService
      - Jwt__Audience=AirlineBookingApp
      - ServiceUrls__FlightService=http://flight-service:8080
    depends_on:
      postgres:
        condition: service_healthy

  booking-service:
    build: ./BookingService
    container_name: airline_booking
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=AirlineBookingDB;Username=airline;Password=airline123;
      - Jwt__Key=AirlineBooking_SuperSecret_JWT_Key_2024!
      - Jwt__Issuer=AuthService
      - Jwt__Audience=AirlineBookingApp
      - ServiceUrls__SeatService=http://seat-service:8080
      - ServiceUrls__PassengerService=http://passenger-service:8080
      - InternalApi__Key=SkyBooker_Internal_2024!
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=airline
      - RabbitMQ__Password=airline123
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  passenger-service:
    build: ./PassengerService
    container_name: airline_passenger
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=AirlinePassenger;Username=airline;Password=airline123;
      - Jwt__Key=AirlineBooking_SuperSecret_JWT_Key_2024!
      - Jwt__Issuer=AuthService
      - Jwt__Audience=AirlineBookingApp
      - InternalApi__Key=SkyBooker_Internal_2024!
    depends_on:
      postgres:
        condition: service_healthy

  notification-service:
    build: ./NotificationService
    container_name: airline_notification
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=AirlineNotification;Username=airline;Password=airline123;
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=airline
      - RabbitMQ__Password=airline123
      - Jwt__Key=AirlineBooking_SuperSecret_JWT_Key_2024!
      - Jwt__Issuer=AuthService
      - Jwt__Audience=AirlineBookingApp
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  airline-frontend:
    build: ./airline-frontend
    container_name: airline_ui
    ports:
      - "4200:80"
    depends_on:
      - api-gateway

volumes:
  postgres_data:
